name: Deploy to Firebase Hosting on push to main

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
    concurrency:
      group: firebase-hosting-deploy
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js (static export)
        run: npm run build

      - name: Verify build output exists
        run: |
          if [ ! -d "out" ]; then echo "out/ not found. Ensure next.config.ts has output: 'export'"; exit 1; fi

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: npx firebase-tools@latest deploy --only hosting --project chat-application-1d2dc --non-interactive
