name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # No build step since repo currently serves static files from public/
      - uses: w9jds/firebase-action@v13.22.0
        with:
          args: deploy --only hosting --project chat-application-1d2dc
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
